# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.3"

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
  end


# CLEAN
  desc "Cleans the project"
  lane :osclean do
      xcclean
  end

# BUILD
  desc "Builds the project"
  lane :osbuild do
      xcbuild
  end

# TESTS
  desc "Runs all the tests"
  lane :test do
    scan(device: "iPhone 11")
	slack(
  		message: "App successfully runned tests",
  		channel: "#test_fastlane", 
  		success: true
	)
  end

# CUSTOMIZED TESTS 
	desc "Runs the tests with custom settings"

	lane :ostest do
# run_tests # ⚠️ [15:49:35]: Could not find action, lane or variable 'run_tests'. 
        scan(project: "KanjiList.xcodeproj",
             code_coverage: true,
             device: "iPhone 11"
        )
        #workspace: "Example.xcworkspace"
        #xctestrun:"KanjiList/TestPlan.xctestrun",
        #devices: ["iPhone 11", "iPad Pro"])
end


# SUBMIT BETA
  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    xcclean
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

# DEPLOY
  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
